name: DevTinder Frontend CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Get Code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm install

      - name: Build Application
        run: npm run build