name: DevTinder Frontend CI/CD

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: Dev_Tinder

    steps:
      - name: Get Code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm install

      - name: Build Application
        run: npm run build

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}

          script: |
            cd ~/devTinderFrontend

            git pull origin master

            cd Dev_Tinder

            docker build --no-cache -t devtinder-frontend .

            docker rm -f devtinder-frontend || true

            docker run -d \
              --name devtinder-frontend \
              --network devtinder-network \
              --restart unless-stopped \
              -p 80:80 \
              devtinder-frontend
